// Production build: bundles the server into dist/.
//
//   npm run build        -> dist/server.js (entry), dist/app.js (+ source map)
//   npm run start:prod   -> NODE_ENV=production node dist/server.js
//
// npm packages are NOT bundled (they're loaded from node_modules at runtime -
// install production deps with `npm ci --omit=dev`). The build fails on any
// syntax error or unresolved local import, so a broken commit can't produce
// a deployable artifact. The migration scripts in scripts/ still run from
// source.
import { build } from "esbuild";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outdir = path.join(root, "dist");

fs.rmSync(outdir, { recursive: true, force: true });

const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));

// Why two files: in a bundle, every `import` of an npm package is hoisted
// above ALL of the app's own code. src/compat/slowBufferShim.js must run
// before jsonwebtoken is loaded (see that file) - in src/ the import order
// guarantees it, but bundled, jsonwebtoken would load first and crash on
// newer Node versions. So dist/server.js runs the shim, then loads the
// bundled app with a dynamic import, which can't be hoisted.
const shared = {
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node20",
  packages: "external",
  legalComments: "none",
  logLevel: "warning",
};

await build({
  ...shared,
  entryPoints: [path.join(root, "src/compat/slowBufferShim.js")],
  outfile: path.join(outdir, "compat.js"),
});

const result = await build({
  entryPoints: [path.join(root, "src/index.js")],
  outfile: path.join(outdir, "app.js"),
  bundle: true,
  platform: "node",
  format: "esm", // the server uses top-level await
  target: "node20",
  packages: "external",
  sourcemap: true, // stack traces point at the original src/ files
  minify: false, // readable production logs/traces matter more than size here
  legalComments: "none",
  logLevel: "warning",
  metafile: true,
  banner: { js: `// ${pkg.name} ${pkg.version} - built ${new Date().toISOString()} from src/ by scripts/build.mjs` },
});

fs.writeFileSync(
  path.join(outdir, "server.js"),
  `// ${pkg.name} ${pkg.version} production entry (generated by scripts/build.mjs).
// Node compatibility shims first, THEN the app - see scripts/build.mjs.
import "./compat.js";
await import("./app.js");
`
);

const bytes = fs.statSync(path.join(outdir, "app.js")).size;
const modules = Object.keys(result.metafile.inputs).length;
console.log(`Built dist/server.js -> dist/app.js (${(bytes / 1024).toFixed(0)} KB from ${modules} source modules).`);
